# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: UiPathTest@6
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'UiPath_Cloud_Connection'
    projectKey: 'ETT'
    testSet: 'Login'
    attachRobotLogs: true