# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Nitin'
  demands:
  - Agent.Name -equals AgentNitin

steps:                   # <--- You are missing this line!
- task: UiPathTest@6     # <--- Ensure this is indented under steps
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'UiPath_Cloud_Connection'
    projectKey: 'ETT'
    testSet: 'uipath.CICD'
    folderName: 'Testing'