# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
 
pool:
  name: 'Nitin'
  agent: 'AgentNitin'


steps:
- task: UiPathPack@6
  inputs:
    projectJsonPath: 'https://github.com/nitch446/CICD/blob/main/project.json'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@6
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'UiPath_Cloud_Connection'
    projectKey: 'ETT'
    testSet: 'Login'
    attachRobotLogs: true