# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Nitin'
  agent: 'AgentNitin'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathTest@6
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath_Cloud_Connection'
    testProjectPath: 'project.json'
    folderName: 'Testing'
    testReportDestination: 'result.json'
    traceLevel: 'Verbose'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'